@startuml

skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam linetype ortho
top to bottom direction
allowmixing

artifact "Ontologie\n(Mappingprofil,\nRegeln & Vokabular)" as Ontology
database "Persistent Knowledge Graph" as KGDatabase

package "Ontologie- und Wissensgraph-Komponente" {
  class KGLoader {
    +build_gvl_index_from_objects(): None
    +ingest_programs_from_mapping_json(): None
    +ingest_io_mappings(): None
    +ingest_gvl_globals(): None
    +save(): None
  }

  class KGManager {
    +load(): Graph
    +analyze_unused_elements(): None
    +generate_reports(): None
    +save(output_path): Path
  }

  class KGStore {
    +graph: Graph
  }

  KGLoader --> KGStore : befüllt
  KGManager --> KGStore : analysiert\nund erweitert
}

Ontology ..> KGLoader
KGStore <..> KGDatabase : persistiert / lädt

@enduml
